---
- name: Configure Bash completion
  block:

    - name: Completion for the Bash shell present
      ansible.builtin.apt:
        pkg:
          - bash-completion
        state: present

    - name: Directory /etc/bash_completion.d present
      ansible.builtin.file:
        path: /etc/bash_completion.d
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Generate a Bash completion script
      shell: |
        set -e -o pipefail
        /root/yq_linux_{{ ansible_local.dpkg.arch }} shell-completion bash > /root/yq-completion.bash
      args:
        executable: "{{ ansible_local.bash.path }}"
      check_mode: false
      changed_when: false

    - name: Bash completion script in place
      copy:
        src: /root/yq-completion.bash
        dest: /etc/bash_completion.d/yq
        remote_src: true
        mode: 0755
        owner: root
        group: root
        validate: "{{ ansible_local.bash.path }} -e %s"

  tags:
    - yq
...
