---
- name: Configure Bash completion
  block:

    - name: Completion for the Bash shell present
      ansible.builtin.apt:
        pkg:
          - bash-completion
        state: present

    - name: Directory /etc/bash_completion.d present
      ansible.builtin.file:
        path: /etc/bash_completion.d
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Run which bash
      command: which bash
      check_mode: false
      changed_when: false
      register: yq_which_bash
      failed_when: yq_which_bash.stdout is not regex('\/bash$')

    - name: Set a variable for the path to Bash
      set_fact:
        yq_bash: "{{ yq_which_bash.stdout }}"

    - name: Generate a Bash completion script
      shell: |
        set -e -o pipefail
        /root/yq_linux_{{ ansible_local.dpkg_arch.arch }} shell-completion bash > /root/yq-completion.bash
      args:
        executable: "{{ yq_bash }}"

    - name: Bash completion script in place
      copy:
        src: /root/yq-completion.bash
        dest: /etc/bash_completion.d/yq
        remote_src: true
        mode: 0755
        owner: root
        group: root
        validate: "{{ yq_bash }} -e %s"

  tags:
    - yq
...
