# Copyright 2022-2023 Chris Croome
#
# This file is part of the Webarchitects yq Ansible role.
#
# The Webarchitects yq Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects yq Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects yq Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Skip the tasks in this role as yq is false
  ansible.builtin.debug:
    msg: "The yq variable need to be true for the tasks in this role to run."
  when: not yq | bool
  tags:
    - yq

- name: Install or upgrade yq
  block:

    - name: Include verify variables tasks
      ansible.builtin.include_tasks: verify.yml
      when:
        - yq_verify | bool
        - ansible_version.full is version('2.11', '>=')

    - name: Include apt role local fact tasks if variables are not defined  # noqa: var-naming[no-role-prefix]
      ansible.builtin.include_role:
        name: apt
        tasks_from: local_facts.yml
      vars:
        apt: true
        apt_local_facts: true
        apt_local_facts_files:
          - name: bash.fact
            state: present
          - name: dpkg.fact
            state: present
      when: >-
        ( ansible_local.dpkg.arch is not defined ) or
        ( ansible_local.bash.path is not defined )

    - name: Which yq
      ansible.builtin.command: which yq
      check_mode: false
      changed_when: false
      register: yq_which
      failed_when: yq_which.rc is not regex('^0|1$')

    - name: Check the yq version
      ansible.builtin.include_tasks: version.yml
      when: yq_which.rc == 0

    - name: Find the latest version of yq
      block:

        - name: Use a HEAD request to get the latest redirect URL
          ansible.builtin.uri:
            url: https://github.com/mikefarah/yq/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: yq_latest_headers

        - name: Set a fact for the latest version of yq
          ansible.builtin.set_fact:
            yq_proposed: "{{ yq_latest_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"

      when: yq_version == "latest"

    - name: Set a fact for the proposed version of yq when not latest
      ansible.builtin.set_fact:
        yq_proposed: "{{ yq_version | string }}"
      when: ( yq_proposed is not defined ) or ( yq_version != "latest" )

    - name: Download yq
      ansible.builtin.get_url:
        url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_proposed }}/yq_linux_{{ ansible_local.dpkg.arch }}"
        dest: "/root/yq_linux_{{ ansible_local.dpkg.arch }}"
        mode: "0700"
        owner: root
        group: root
        timeout: 120
      check_mode: false
      changed_when: false
      register: yq_download

    - name: Configure Bash completion for yq
      ansible.builtin.include_tasks: bash.yml
      when:
        - yq_completion is defined
        - yq_completion != []
        - ( "bash" in yq_completion )

    - name: Copy yq into place
      ansible.builtin.copy:
        src: "/root/yq_linux_{{ ansible_local.dpkg.arch }}"
        dest: /usr/local/bin/yq
        remote_src: true
        mode: "0755"
        owner: root
        group: root
        validate: "%s -V"

    - name: Check the yq version
      ansible.builtin.include_tasks: version.yml

    - name: Debug the install version
      ansible.builtin.debug:
        msg: "yq version {{ yq_proposed }} is installed"

  when: yq | bool
  tags:
    - yq
...
