---
- name: Install or upgrade yq
  block:

    - name: Include local facts tasks
      ansible.builtin.include_tasks: local_facts.yml
      when: ( ansible_local.dpkg is not defined ) or ( ansible_local.bash is not defined )

    - name: Which yq
      ansible.builtin.command: which yq
      check_mode: false
      changed_when: false
      register: yq_which
      failed_when: yq_which.rc is not regex('^0|1$')

    - name: Check the yq version
      ansible.builtin.include_tasks: version.yml
      when: yq_which.rc == 0

    - name: Find the latest version of yq
      block:

        - name: Use a HEAD request to get the latest redirect URL
          ansible.builtin.uri:
            url: https://github.com/mikefarah/yq/releases/latest
            method: HEAD
            status_code: 302
            follow_redirects: none
          check_mode: false
          changed_when: false
          register: yq_latest_headers

        - name: Set a fact for the latest version of yq
          ansible.builtin.set_fact:
            yq_proposed: "{{ yq_latest_headers.location | urlsplit('path') | basename | regex_replace('^v') | string }}"

      when: yq_version == "latest"

    - name: Set a fact for the proposed version of yq when not latest
      ansible.builtin.set_fact:
        yq_proposed: "{{ yq_version | string }}"
      when: ( yq_proposed is not defined ) or ( yq_version != "latest" )

    - name: Download yq
      ansible.builtin.get_url:
        url: "https://github.com/mikefarah/yq/releases/download/v{{ yq_proposed }}/yq_linux_{{ ansible_local.dpkg.arch }}"
        dest: "/root/yq_linux_{{ ansible_local.dpkg.arch }}"
        mode: 0700
        owner: root
        group: root
        timeout: 120
      register: yq_download

    - name: Configure Bash completion for yq
      ansible.builtin.include_tasks: bash.yml
      when: ( yq_completion is defined ) and ( yq_completion != [] ) and ( "bash" in yq_completion )

    - name: Copy yq into place
      ansible.builtin.copy:
        src: "/root/yq_linux_{{ ansible_local.dpkg.arch }}"
        dest: /usr/local/bin/yq
        remote_src: true
        mode: 0755
        owner: root
        group: root
        validate: "%s -V"

    - name: Check the yq version
      ansible.builtin.include_tasks: version.yml

    - name: Debug the install version
      ansible.builtin.debug:
        msg: "yq version {{ yq_proposed }} is installed"

  when: yq
  tags:
    - yq
...
